### ISSUE TITLE
Please incorporate BiDi (CTL) support at Qt library level

### ISSUE THREAD

**Issue by faridcher** [srazi/bidiTeXmaker#1]
Hi,

Many applications rely on qt library for their GUIs. Having [complex text layout/rendering](https://en.wikipedia.org/wiki/Complex_Text_Layout) (CTL) implemented at Qt level makes every Qt application (e.g. [QGIS](https://github.com/qgis/QGIS/issues/39232)) BiDi enabled not just TeXMaker. At your discretion, please submit your work/changes to the upstream [qt development branch](https://bugreports.qt.io/browse/QTBUG-57743?jql=text%20~%20CTL%20OR%20text%20~%20BIDI).

thanks

**Comment by srazi** [comment]
Well, Qt has BiDi support, what I do here is adding Unicode control characters to text and it is completely specific to the TeX markup language so there is not something that we submit to Qt development branch. If you want, I can check your issue with QGIS.
